spring:
  application:
    name: SpringObservality

management:
  endpoints:
    web:
      exposure:
#        include: health, prometheus
        include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s