spring:
  application:
    name: SpringObservality

management:
  endpoints:
    web:
      exposure:
#        include: health, prometheus
        include: "*"
  endpoint:
    health:
      show-details: always


  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s