spring:
  application:
    name: SpringObservality

management:
  endpoints:
    web:
      exposure:
#        include: health, prometheus
#        include: "*"
        include: health, metrics
  endpoint:
    health:
      show-details: always


  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s


  metrics:
    tags:
      department: ${SERVICE_DEPARTMENT:software}
      team: ${SERVICE_TEAM:greeting}
      service: ${spring.application.name}
      env: ${SERVICE_ENV:dev}
      region: ${SERVICE_REGION:eu-west-1}
      instance.id: ${SERVICE_INSTANCE_ID:1}